<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function countNbArticles()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('COUNT(a.id)');
          

        return $qb->getQuery()->getSingleScalarResult();
    }
}
