<?php

namespace AppBundle\Repository;
use UserBundle\Entity\User;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function countNbArticles()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('COUNT(a.id)');
          

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function listeArticlesNonSupprimer(User $user = null)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->orderBy('a.id', 'desc')
            ->andWhere('a.deleted IS NULL');

        if ($user !== null) {
            $qb->andWhere('o.author = :author');
            $qb->setParameter('author', $user);
        }

        return $qb->getQuery()->getResult();
    }
}
