<?php

namespace AppBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function countNbObservations()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('COUNT(b.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
