<?php

namespace AppBundle\Repository;

use InvalidArgumentException;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use UserBundle\Entity\User;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPublishedObsvervationForOiseau($oiseau, $minDate)
    {
        $qd = $this->createQueryBuilder('o');
        if ($oiseau !== null) {
            $qd->where('o.oiseau = :oiseau')
            ->setParameter('oiseau', $oiseau);
        }
        if ($minDate !== null) {
            $qd->andWhere('o.date >= :dateFrom')
            ->setParameter('dateFrom', $minDate);
        }

        $qd->andWhere('o.publish IS NOT NULL')
        ->leftJoin('o.oiseau', 'bird')
        ->addSelect('bird')
        ->leftJoin('o.author', 'auth')
        ->addSelect('auth');

        return $qd
            ->getQuery()
            ->getResult();
    }

    public function findAllPublishedWithOiseauAndAuthor()
    {
        $qd = $this->createQueryBuilder('o')
        ->where('o.publish IS NOT NULL')
        ->leftJoin('o.oiseau', 'bird')
        ->addSelect('bird')
        ->leftJoin('o.author', 'auth')
        ->addSelect('auth');

        return $qd
            ->getQuery()
            ->getResult();
    }

    public function countNbObservations(User $user = null)
    {
        $qb = $this->createQueryBuilder('o');
        $qb
            ->select('COUNT(o.id)')
            ->andWhere('o.deleted IS NULL');
        ;

        if ($user !== null) {
            $qb->andWhere('o.author = :author');
            $qb->setParameter('author', $user);
        }

        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function listeObservationsNonSupprimer(User $user = null)
    {
        $qb = $this->createQueryBuilder('o');
        $qb
            ->orderBy('o.id', 'desc')
            ->andWhere('o.deleted IS NULL');

        if ($user !== null) {
            $qb->andWhere('o.author = :author');
            $qb->setParameter('author', $user);
        }

        return $qb->getQuery()->getResult();
    }

}
