<?php

namespace AppBundle\Repository;

/**
 * OiseauTaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OiseauTaxrefRepository extends \Doctrine\ORM\EntityRepository
{
}
