<?php

namespace AppBundle\Repository;

/**
 * OiseauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OiseauRepository extends \Doctrine\ORM\EntityRepository
{
}
