<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function countNbUsers()
    {
        $qb = $this->createQueryBuilder('u');
        $qb->select('COUNT(u.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
